<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2c3421a0-9a71-4ae2-bbe0-0c50192adeea</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniAlbum.Application\MiniAlbum.Application.csproj" />
    <ProjectReference Include="..\MiniAlbum.Infrastructure\MiniAlbum.Infrastructure.csproj" />
  </ItemGroup>

</Project>
